repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-json
    - id: pretty-format-json
      args:
        - "--autofix"
        - "--indent=2"
        - "--no-sort-keys"
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/crate-ci/typos
  rev: v1.16.25
  hooks:
    - id: typos
